version: '3'
networks:
  development:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.18.0.0/24

services:
  user-mysql:
    container_name: ${USERS_MYSQL_DB_ADDRESS}
    image: mysql:8.0.21
    ports:
      - ${USERS_MYSQL_DB_EXPOSED_PORT}:${USERS_MYSQL_DB_PORT}
    networks:
      - development
    environment:
      MYSQL_ROOT_PASSWORD: ${USERS_MYSQL_DB_PASSWORD}
      MYSQL_DATABASE: ${USERS_MYSQL_DB_NAME}
  user-db-server:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        SERVER_PORT: ${USERS_SERVER_PORT}
    container_name: user-db-server
    image: artofimagination/user-db-server
    ports:
      - ${USERS_SERVER_PORT}:${USERS_SERVER_PORT}
    networks:
      - development
    depends_on: 
      - ${USERS_MYSQL_DB_ADDRESS}
    environment:
      SERVER_PORT: ${USERS_SERVER_PORT}
      MYSQL_DB_ADDRESS: ${USERS_MYSQL_DB_ADDRESS}
      MYSQL_DB_USER: ${USERS_MYSQL_DB_USER-root}
      MYSQL_DB_PORT: ${USERS_MYSQL_DB_PORT}
      MYSQL_DB_PASSWORD: ${USERS_MYSQL_DB_PASSWORD-123secure}
      MYSQL_DB_NAME: ${USERS_MYSQL_DB_NAME-user_database}
      MYSQL_DB_MIGRATION_DIR: ${USERS_MYSQL_DB_MIGRATION_DIR-$GOPATH/src/github.com/artofimagination/mysql-user-db-go-interface/db/migrations/mysql}
